version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: justificantes_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: justificantes-backend:latest
    container_name: justificantes-backend
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123
      - DB_NAME=justificantes_db
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: justificantes-frontend:latest
    container_name: justificantes-frontend
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app  
    depends_on:
      - backend

volumes:
  db_data:
